# Generated by Django 5.1.1 on 2024-09-10 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('f_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.student')),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=100)),
                ('begining', models.TimeField()),
                ('c_num', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.class')),
                ('l_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.teacher')),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.subject')),
            ],
        ),
    ]
